name: conduit_isolate_exec
version: 5.1.5
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  analyzer: ^7.1.0
  glob: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.2
  test_package:
    path: ../isolate_exec_test_packages/test_package
