name: Conduit
repository: https://github.com/conduit-dart/conduit
packages:
  - packages/**
ignore:
  - packages/cli/templates/**
  - packages/tmp/**
  - packages/not_tests/**
  - packages/runtime_test_packages/**
  - packages/isolate_exec_test_packages/**
command:
  version:
    linkToCommits: true
scripts:
  test-unit:
    run: melos exec -c1 --fail-fast --ignore "*common*" --ignore "*application*" --ignore "*dependency*" -- "dart test -r failures-only"
    packageFilters:
      noPrivate: true
  test-with-coverage:
    run: melos exec --ignore "*common*" --ignore "*application*" --ignore "*dependency*" -- "dart MELOS_ROOT_PATH/utils/unused_port.dart | dart pub global run coverage:test_with_coverage --port -"
    packageFilters:
      noPrivate: true
  analyze: melos exec -- dart analyze .
  upgrade: melos exec -- dart pub upgrade
  outdated:
    run: melos exec -- "dart pub outdated"
  activate-all:
    run: melos exec -- "dart pub global activate -spath MELOS_PACKAGE_PATH"
    packageFilters:
      noPrivate: true
  deactivate-all:
    run: melos exec -- "dart pub global deactivate MELOS_PACKAGE_NAME"
    packageFilters:
      noPrivate: true
  cache-source:
    run: melos exec -- "mkdir -p '$PUB_CACHE/hosted/pub.dev/MELOS_PACKAGE_NAME-MELOS_PACKAGE_VERSION' && cp -rf 'MELOS_PACKAGE_PATH'/* '$PUB_CACHE/hosted/pub.dev/MELOS_PACKAGE_NAME-MELOS_PACKAGE_VERSION'"
    packageFilters:
      noPrivate: true
  cache-source-win:
    run: melos exec -- mkdir %PUB_CACHE%\hosted\pub.dev\MELOS_PACKAGE_NAME-MELOS_PACKAGE_VERSION && melos exec -- xcopy MELOS_PACKAGE_PATH %PUB_CACHE%\hosted\pub.dev\MELOS_PACKAGE_NAME-MELOS_PACKAGE_VERSION /Y /s /e
    packageFilters:
      noPrivate: true
  hard-clean:
    run: melos exec -- "rm -rf 'MELOS_PACKAGE_PATH/.dart_tool' 'MELOS_PACKAGE_PATH/pubspec.lock'"
  gen-docs:
    run: |
      melos exec --ignore "*common*" --ignore "fs_test_agent" -- "dart doc"
    packageFilters:
      noPrivate: true
  fix:
    run: melos exec --fail-fast --ignore "*common*" --ignore "*application*" --ignore "*dependency*" -- "dart fix --apply ."
  sync-version:
    run: |
      export v=`dart pub deps -s list | grep conduit_workspace | awk '{print $2}' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+'`; \
      melos version  --yes -V conduit:$v \
                          -V conduit_codable:$v \
                          -V conduit_common:$v \
                          -V conduit_config:$v \
                          -V conduit_core:$v \
                          -V conduit_isolate_exec:$v \
                          -V conduit_open_api:$v \
                          -V conduit_password_hash:$v \
                          -V conduit_postgresql:$v \
                          -V conduit_runtime:$v \
                          -V conduit_test:$v \
                          -V fs_test_agent:$v
