site_name: Conduit
theme:
  name: readthedocs
markdown_extensions:
  - codehilite
  - markdown.extensions.admonition
repo_url: https://github.com/conduit-dart/conduit
site_description: Documentation for Conduit, a Dart server-side framework.
copyright: Maintained by conduit-dart team
nav:
  - Home: 'README.md'
  - Getting Started: 'getting_started.md'
  - Core Concepts: 'core_concepts.md'
  - Tour: 'tour.md'
  - Tutorial:
    - '1. Getting Started': 'tut/getting-started.md'
    - '2. Reading from a Database': 'tut/executing-queries.md'
    - '3. Storing Data in a Database': 'tut/storing-data.md'
    - '4. Configuration and Testing': 'tut/writing-tests.md'
    - '5. Authentication and Authorization': 'tut/oauth2.md'
  - API: '*include ./packages/*/mkdocs.yml'
  - Best Practices: 'best_practices.md'
  - Guides:
    - 'Application Configuration and Behavior':
        - 'Overview': 'application/README.md'
        - 'Starting and Stopping Applications': 'application/channel.md'
        - 'Configuring an Application and its Environment': 'application/configure.md'
        - 'Application and Project Structure': 'application/structure.md'
        - 'Multi-threading': 'application/threading.md'
    - 'Handling HTTP Requests':
        - 'Overview': 'http/README.md'
        - 'Handling Requests and Sending Response': 'http/controller.md'
        - 'Serializing Request and Response Bodies': 'http/request_and_response.md'
        - 'Routing': 'http/routing.md'
        - 'Request Binding with Resource Controllers': 'http/resource_controller.md'
        - 'Serving Files and Caching': 'http/serving_files.md'
        - 'Websockets': 'http/websockets.md'
        - 'Uploading Files': 'http/file_upload.md'
    - 'Databases and ORM':
        - 'Overview': 'db/README.md'
        - 'Connecting to a Database': 'db/connecting.md'
        - 'Modeling Data and Relationships': 'db/modeling_data.md'
        - 'Serialization and Deserialization': 'db/serialization.md'
        - 'Basic Queries': 'db/executing_queries.md'
        - 'Advanced Queries': 'db/advanced_queries.md'
        - 'Transactions': 'db/transactions.md'
        - 'Validations': 'db/validations.md'
        - 'Migration and Tooling': 'db/db_tools.md'
        - 'JSON Document Storage': 'db/json_columns.md'
    - 'Authorization and OAuth 2.0':
        - 'Overview': 'auth/README.md'
        - 'Setting up Authorization': 'auth/server.md'
        - 'Protecting Routes': 'auth/authorizer.md'
        - 'Issuing Access Tokens': 'auth/controllers.md'
        - 'Managing OAuth 2.0 Clients': 'auth/cli.md'
        - 'OAuth 2.0 Scoping': 'auth/auth_scopes.md'
        - 'What is OAuth 2.0?': 'auth/what_is_oauth.md'
    - 'Development and Testing':
        - 'Overview': 'testing/README.md'
        - 'Writing Tests': 'testing/tests.md'
        - 'Testing with the ORM and OAuth 2.0': 'testing/mixins.md'
        - 'Using the Debugger': 'testing/debugger.md'
        - 'Developing Client Applications': 'testing/clients.md'
        - 'Mocking Services': 'testing/mock.md'
    - 'OpenAPI Documentation':
        - 'Overview': 'openapi/README.md'
        - 'Creating an OpenAPI Document': 'openapi/cli.md'
        - 'Documenting Components': 'openapi/components.md'
        - 'Documenting Endpoint Controllers': 'openapi/endpoint.md'
        - 'Documenting Middleware Controllers': 'openapi/middleware.md'
    - 'Command-line Tooling':
        - 'Overview': 'cli/README.md'
        - 'Creating Applications': 'cli/create.md'
        - 'Running Applications': 'cli/running.md'
        - 'Generating an OpenAPI/Swagger Specification': 'cli/document.md'
    - 'Deployment':
        - 'Overview': 'deploy/README.md'
        - 'Creating a Conduit Executable': 'deploy/build.md'
        - 'Deploy Locally (VM)': 'deploy/deploy_local.md'
        - 'Deploying with Docker and Kubernetes (VM)': 'deploy/deploy_docker.md'
        - 'Deploy on Heroku (VM)': 'deploy/deploy_heroku.md'
        - 'Deploy on AWS (VM)': 'deploy/deploy_aws.md'
        - 'Deploying without aqueduct serve (VM)': 'deploy/script.md'
    - Migration:
        - 'migration/4.1.8.md'
  - Snippets:
    - 'Overview': 'snippets/README.md'
    - 'HTTP': 'snippets/http.md'
    - 'ORM': 'snippets/orm.md'
    - 'Authentication and Authorization': 'snippets/auth.md'
    - 'Testing': 'snippets/test.md'
plugins:
  - monorepo
